// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfwavjbqiggjqxclauae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1md2F2amJxaWdnanF4Y2xhdWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODgyNDIsImV4cCI6MjA2NjQ2NDI0Mn0.MMgLxP_pu3QBaLvdHycKSTmAj4bpwTd4B7m5msxNtBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);